version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis

  celery:
    build: .
    command: celery -A webapp.celery_worker worker --loglevel=info --pool=solo
    depends_on:
      - redis

  flower:
    build: .
    command: celery -A webapp.celery_worker flower --port=5555
    ports:
      - "5555:5555"
    environment:
      FLOWER_UNAUTHENTICATED_API: "1"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
